- name: creating the bastion host
  hosts: localhost
  become: true
  connection: local
  gather_facts: false
  tasks:
    - name: importing the bastion_setup variables
      include_vars: vars/bastion_setup

    - name: importing the vpc_setup variables
      include_vars: vars/vpc_setup

    - name: importing the vpc-output.var
      include_vars: vars/vpc-output.var

    - name: creating the key pair for bastion host
      ec2_key:
        name: vprofile-key
        region: "{{region}}"
        state: present
      register: keyout

    - debug:
        var: keyout

    - name: saving the key pairs
      copy:
        content: "{{keyout.key.private_key}}"
        dest: "./vprofile-key.pem"
        mode: 0600
      when: keyout.changed

    - name: creating the securty group for bastion host
      ec2_group:
        vpc_id: "{{vpcoutid}}"
        region: "{{region}}"
        state: present
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
      register: basionsg_out

    - name: creating the bastion host
      ec2:
        key_name: vprofile-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 200
        instance_tags:
          Name: bastion-host
          project: vprofile
          owner: devopsteam
        exact_count: 1
        count_tag:
          Name: bastion-host
          project: vprofile
          owner: devopsteam
          group_id: "{{bastionsg_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastionhost_out

    - name:
      blockinfile:
        path: vars/vpc-output.var
        backup: yes
        block: |
          bastionsgid: {{bastionsg_out.group_id}}
